[
  "[ERROR] Instance failed constraint ref-1 \"SHALL have a contained resource if a local reference is provided\"(further diagnostics: reference.startsWith(\u0027#\u0027).not() or (reference.substring(1).trace(\u0027url\u0027) in %rootResource.contained.id.trace(\u0027ids\u0027))) (at Bundle.entry[0].resource[0].contained[0].target[0])",
  "[ERROR] Contained reference (#) is not resolvable (at Bundle.entry[0].resource[0].contained[0].target[0])",
  "[WARNING] Cannot resolve reference # (at Bundle.entry[0].resource[0].contained[0].target[0])"
]